name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11 # 替换为你的 Java 版本
      uses: actions/setup-java@v4
      with:
        java-version: '11' # 替换为你的 Java 版本
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven # 运行 Maven 构建命令
      run: mvn -B package --file pom.xml

